version: 2
jobs:
  build:
    working_directory: /usr/src/apidocs
    docker:
      - image: python:2.7.13
    branches:
    only:
      - master
    steps:
      - checkout
      - run:
          name: Install slicer-apidocs-builder
          command: |
            pip install git+https://github.com/Slicer/slicer-apidocs-builder
      - run:
          name: Set GitHub status to 'pending'
          command: |
            slicer-apidocs-builder \
              --status-update-state pending \
              --status-update-repo-name ${SLICER_REPO_NAME} \
              --status-update-revision ${SLICER_REPO_REVISION} \
              --status-update-target-url ${CIRCLE_BUILD_URL}

      - run:
          name: Display Environment Variables
          command: |
            echo "SLICER_REPO_NAME ...........: ${SLICER_REPO_NAME}"
            echo "SLICER_REPO_REVISION .......: ${SLICER_REPO_REVISION}"
            echo "SLICER_REPO_BRANCH .........: ${SLICER_REPO_BRANCH}"
            echo "SLICER_REPO_TAG: ...........: ${SLICER_REPO_TAG}"
            echo "PUBLISH_GITHUB_REPO_NAME ...: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
      - run:
          name: Install Doxygen
          command: |
            (
              apt-get update
              apt-get install -y --no-install-recommends graphviz
              .circleci/install-doxygen.sh
            ) \
            ||
            (
              slicer-apidocs-builder \
                --status-update-state failure \
                --status-update-repo-name ${SLICER_REPO_NAME} \
                --status-update-revision ${SLICER_REPO_REVISION} \
                --status-update-target-url ${CIRCLE_BUILD_URL}
              exit 1
            )
      - run:
          name: Generate Documentation
          command: |
            (
              slicer-apidocs-builder \
                --slicer-repo-name ${SLICER_REPO_NAME} \
                --slicer-repo-branch ${SLICER_REPO_BRANCH} \
                --slicer-repo-tag "${SLICER_REPO_TAG}"
            ) \
            ||
            (
              slicer-apidocs-builder \
                --status-update-state failure \
                --status-update-repo-name ${SLICER_REPO_NAME} \
                --status-update-revision ${SLICER_REPO_REVISION} \
                --status-update-target-url ${CIRCLE_BUILD_URL}
              exit 1
            )
      - run:
          name: Publish documentation
          command: |
            (
              slicer-apidocs-builder \
                --skip-build \
                --publish-github-repo-name "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" \
                --publish-github-repo-branch gh-pages
            ) \
            ||
            (
              slicer-apidocs-builder \
                --status-update-state failure \
                --status-update-repo-name ${SLICER_REPO_NAME} \
                --status-update-revision ${SLICER_REPO_REVISION} \
                --status-update-target-url ${CIRCLE_BUILD_URL}
              exit 1
            )
      - run:
          name: Set GitHub status to 'success'
          command: |
            slicer-apidocs-builder \
              --status-update-state success \
              --status-update-repo-name ${SLICER_REPO_NAME} \
              --status-update-revision ${SLICER_REPO_REVISION} \
              --slicer-repo-branch ${SLICER_REPO_BRANCH} \
              --slicer-repo-tag "${SLICER_REPO_TAG}" \
              --status-update-target-url "https://slicer.github.com/apidocs.slicer.org"

