version: 2
jobs:
  build:
    working_directory: /usr/src/apidocs
    docker:
      - image: python:2.7.13
    branches:
    only:
      - master
    steps:
      - checkout
      - run:
          name: Display Environment Variables
          command: |
            echo "SLICER_REPO_NAME ...........: ${SLICER_REPO_NAME}"
            echo "SLICER_REPO_BRANCH .........: ${SLICER_REPO_BRANCH}"
            echo "SLICER_REPO_TAG: ...........: ${SLICER_REPO_TAG}"
            echo "PUBLISH_GITHUB_REPO_NAME ...: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y --no-install-recommends graphviz
            .circleci/install-doxygen.sh
            pip install git+https://github.com/Slicer/slicer-apidocs-builder
      - run:
          name: Generate Documentation
          command: |
            slicer-apidocs-builder \
              --slicer-repo-name ${SLICER_REPO_NAME} \
              --slicer-repo-branch ${SLICER_REPO_BRANCH} \
              --slicer-repo-tag "${SLICER_REPO_TAG}"
      - deploy:
          name: Publish documentation
          command: |
            slicer-apidocs-builder \
              --skip-build \
              --publish-github-repo-name "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" \
              --publish-github-repo-branch gh-pages

